f_name = input("inter your Full name: ")
age = int(input("inter your age: "))
gender = str(input("inter your sex: "))
country = input("inter your Country: ")
phone_no = int(input("inter your Phone_number: "))
program = input("inter your course: ")
hobby = input("what is your hobby: ")
print("Full Name:   ",f_name)
print("Age      :   ",age)
print("Gender   :   ",gender)
print("Country  :   ",country)
print("Phone    :   ",phone_no)
print("Program  :   ",program)
print("Hobby    :   ",hobby)