
Full_Name = input("Enter Your Full Name: ")
Age = input("Enter Your Age:")
Gender = input("Enter Your Gender:")
Country = input("Enter Your Country Name:")
Phone_Number = input("Enter Your Phone Number:")
Program = input("Enter Your Program: ")
Hobby = input("Enter Your Hobby: ")
print("----- PERSONAL INFORMATION -----")
print("Full Name: ", Full_Name)
print("Age:", Age)
print("Gender:", Gender)
print("Country:", Country)
print("Phone_Number:", Phone_Number)
print("Program:",Program)
print("Hobby:",Hobby)